@extends('layout.app')
@section('title','Submitted Forms')
@section('page-title','Submitted Forms')
@section('page-subtitle','Review applicant employment forms and questionnaires')
@section('content')
@php $prefix=request()->routeIs('hr.*')?'hr':'admin'; @endphp
<div class="card"><div class="card-header d-flex flex-wrap align-items-center justify-content-between gap-3"><div><h4>Applicant Form Submissions</h4><p class="text-muted mb-0">View completed Application for Employment and Questionnaire responses.</p></div><button type="button" id="refreshBtn" class="premium-secondary-btn"><i class="bi bi-arrow-clockwise"></i><span>Refresh Records</span></button></div><div class="card-body"><div class="table-responsive"><table id="dataTable" class="table w-100"><thead><tr><th>Reference</th><th>Applicant</th><th>Position</th><th>Form</th><th>Type</th><th>Submitted</th><th>Action</th></tr></thead></table></div></div></div>
<div class="modal fade" id="viewModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header bg-dark text-white"><div><h5 class="modal-title" id="viewTitle">Submitted Form</h5><small id="viewMeta" class="text-white-50"></small></div><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body" id="answersContainer"></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Close</button></div></div></div></div>
@endsection
@push('styles')<style>.answer-section{margin:18px 0 10px;padding:9px 12px;border-radius:8px;background:#e8ecec;font-size:13px;font-weight:800;text-transform:uppercase}.answer-card{padding:13px 15px;border:1px solid #e8edf3;border-radius:10px;margin-bottom:10px}.answer-label{font-size:12px;font-weight:700;color:#66738a}.answer-value{font-size:14px;color:#17233e;white-space:pre-wrap}</style>@endpush
@push('scripts')
<script>$(function(){const modal=new bootstrap.Modal(document.getElementById('viewModal'));const dataUrl=@json(route($prefix.'.form-submissions.data'));const showUrl=@json(route($prefix.'.form-submissions.show',':id'));const table=$('#dataTable').DataTable({processing:true,responsive:true,ajax:dataUrl,columns:[{data:'reference_no'},{data:'applicant'},{data:'position'},{data:'template'},{data:'type'},{data:'submitted_at'},{data:null,orderable:false,render:(d,t,r)=>`<button class="btn btn-sm btn-danger viewBtn" data-id="${r.id}"><i class="bi bi-eye"></i> View</button>`}]});$('#refreshBtn').on('click',function(){const $button=$(this);const originalHtml=$button.html();$button.prop('disabled',true).html('<span class="spinner-border spinner-border-sm" aria-hidden="true"></span><span>Refreshing...</span>');table.ajax.reload(function(){$button.prop('disabled',false).html(originalHtml);showToast('success','Records refreshed successfully.');},false);});$('#dataTable').on('click','.viewBtn',function(){$.get(showUrl.replace(':id',$(this).data('id')),function(r){$('#viewTitle').text(r.template.name);$('#viewMeta').text(`${r.application.reference_no} · ${r.application.applicant.first_name} ${r.application.applicant.last_name}`);let html='',section=null;(r.answers||[]).forEach(a=>{if(a.section&&a.section!==section){section=a.section;html+=`<div class="answer-section">${section}</div>`;}let value=a.value||'—';if(value.startsWith('application-documents/'))value=`<a href="{{ asset('storage') }}/${value}" target="_blank">Open uploaded file</a>`;html+=`<div class="answer-card"><div class="answer-label">${a.label}</div><div class="answer-value">${value}</div></div>`;});$('#answersContainer').html(html||'<div class="alert alert-light">No answers found.</div>');modal.show();});});});</script>
@endpush
